- name: Enable cgroups
  become: true
  hosts: pies
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:
    - name: Check if cgroups are enabled
      command: cat /boot/cmdline.txt
      register: cmdlineContent
    - name: Enable cgroups
      command: sed -i -e 's/$/ cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory/' /boot/cmdline.txt
      when: "'cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory' not in cmdlineContent.stdout"
      notify:
        - Restart pi
  handlers:
    - name: Restart pi
      ansible.builtin.reboot:
